# -*- coding: utf-8 -*-
"""
Created on Tue Sep 13 13:31:02 2022

@author: Roman Wixinger (roman.wixinger@gmail.com)

Image Analysis: Takes images from the CCD camera and generates plot and reports
from these images. The plots contain 2D gaussian fits which tell us the MOT 
number and the power. The reports are then a collection of results as a table. 
"""

import sys
sys.path.insert(0,'..')

import pandas as pd

from recorders.image_recorder import ImageRecorder
from fit_mot_number import perform_analysis
from analyses.analysis import Analysis
    
    
class ImageAnalysis(Analysis): 
    
    def __init__(self, filepath: str, 
                 image_src: str="../../plots/",  
                 image_extension: str=".png",
                 match: str=".*ccd_detuning.*.xlsx"):
        super(ImageAnalysis, self).__init__(
            recorder=ImageRecorder(filepath, match=match), 
            filepath=filepath, 
            name="Image Analysis",
            image_src=image_src, 
            image_extension=image_extension
            ) 
        
    def _run_analysis(self, df: pd.DataFrame): 
        """ Runs the fit_mot_number algorithm on all images, saves the images
            and saves the fit result in a new table. 
        """
        
        columns = list(df.columns) 
        new_columns = ["R^2"]
        extract_funcs = [lambda s: s["R^2"]]
        new_rows = []
        
        for i, row in df.iterrows(): 
            source = row["filepath"]
            target = self.image_src + "plot_2d_mot_number_{i}" + self.image_extension
            statistics = perform_analysis(source=source, target=target, mode="mot number")
            new_row = list(row) + [func(statistics) for func in extract_funcs]
            new_rows.append(new_row)
            
        df = pd.DataFrame(data=new_rows, columns=columns+new_columns)
        print(df)
        return 
    
    def _enrich_df_with_statistics(df: pd.DataFrame, statistics_list: list[dict]) -> pd.DataFrame: 
        """
        Takes the table from the ImageRecorder and the statistics generated by 
        the fit_mot_data function. Combines the two in an enriched dataframe. 
        
        """
        pass
        
    
if __name__=="__main__": 
    
    folder = "C:\\Users\\roman\\Desktop\\Research_UTokyo\\Data\\mot"
    match = ".*ccd_detuning.*.xlsx"
    
    image_analysis = ImageAnalysis(filepath=folder, match=match)
    image_analysis.run()
    